=== UO301831/Navarra-Desktop/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="https://www.uniovi.es" elementFormDefault="qualified" targetNamespace="https://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="rutas">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ruta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="tipo" />
                <xs:element ref="transporte" />
                <xs:element minOccurs="0" maxOccurs="1" ref="fechaInicio" />
                <xs:element minOccurs="0" maxOccurs="1" ref="horaInicio" />
                <xs:element ref="duracion" />
                <xs:element ref="agencia" />
                <xs:element ref="descripcion" />
                <xs:element ref="personas" />
                <xs:element ref="inicio" />
                <xs:element ref="referencias" />
                <xs:element ref="recomendacion" />
                <xs:element ref="hitos" />
                <xs:element ref="planimetria" />
                <xs:element ref="altimetria" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="nombre"      type="xs:string" />
    <xs:element name="tipo"        type="xs:string" />
    <xs:element name="transporte"  type="xs:string" />
    <xs:element name="fechaInicio" type="xs:date" />
    <xs:element name="horaInicio"  type="xs:time" />
    <xs:element name="duracion"    type="xs:string" />
    <xs:element name="agencia"     type="xs:string" />
    <xs:element name="descripcion" type="xs:string" />
    <xs:element name="personas"    type="xs:string" />
    <xs:element name="planimetria" type="xs:string" />
    <xs:element name="altimetria"  type="xs:string" />

    <xs:element name="recomendacion">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0" />
                <xs:maxInclusive value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="inicio">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="lugar" />
                <xs:element ref="direccion" />
                <xs:element ref="coordenadas" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="lugar"     type="xs:string" />
    <xs:element name="direccion" type="xs:string" />

    <xs:element name="coordenadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="longitud" />
                <xs:element ref="latitud" />
                <xs:element ref="altitud" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="longitud" type="xs:decimal" />
    <xs:element name="latitud"  type="xs:decimal" />

    <xs:element name="altitud">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="referencia" type="xs:anyURI" />

    <xs:element name="hitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="5" maxOccurs="unbounded" ref="hito" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="hito">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" ref="nombre" />
                <xs:element minOccurs="0" maxOccurs="1" ref="descripcion" />
                <xs:element ref="coordenadas" />
                <xs:element ref="distancia" />
                <xs:element minOccurs="0" maxOccurs="1" ref="fotos" />
                <xs:element minOccurs="0" maxOccurs="1" ref="videos" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="distancia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="unidades" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="fotos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="5" ref="foto" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="foto" type="xs:string" />

    <xs:element name="videos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="3" ref="video" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="video" type="xs:string" />

</xs:schema>

=== UO301831/Navarra-Desktop/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="https://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://www.uniovi.es rutas.xsd">
    <!-- ============================ RUTA 1 - Foz de Lumbier ================================ -->
    <ruta>
        <nombre>Ruta de la Foz de Lumbier, Ermita de Piedra y Arcos de Piedra</nombre>
        <tipo>Paisajística</tipo>
        <transporte>A pie</transporte>
        <fechaInicio>2026-07-15</fechaInicio>
        <horaInicio>08:30:00</horaInicio>
        <duracion>6 horas 16 minutos</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Caminata circular de un día partiendo desde el poblado de Lumbier. Se recorren los principales puntos de interés. No habría problemas en avanzar para gente acostumbrada a este tipo de senderos.</descripcion>
        <personas>Personas en buena forma física</personas>

        <inicio>
            <lugar>Hotel Iru - Bide</lugar>
            <direccion>Av. de Bijues, s/n</direccion>
            <coordenadas>
                <longitud>-1.310790</longitud>
                <latitud>42.650934</latitud>
                <altitud unidad="m">429</altitud>
            </coordenadas>
        </inicio>

        <referencias>
            <referencia>https://www.visitnavarra.es/es/foz-de-lumbier</referencia>
            <referencia>https://es.wikiloc.com/rutas-senderismo/navarra-foz-de-lumbier-ermita-de-la-trinidad-arcos-de-piedra-trek-1d-175574249</referencia>
            <referencia>https://lumbier.com/la-foz-de-lumbier/</referencia>
        </referencias>

        <recomendacion>7</recomendacion>

        <hitos>

            <hito>
                <coordenadas>
                    <longitud>-1.311253</longitud>
                    <latitud>42.650330</latitud>
                    <altitud unidad="m">428.7</altitud>
                </coordenadas>
                <distancia unidades="m">77</distancia>
            </hito>

            <hito>
                <nombre>Puente de los hierros</nombre>
                <descripcion>Puente de hierro sobre el rio Irati, vestigio de la antigua via ferrea del Irati reconvertida en sendero peatonal. Desde el puente se obtienen las primeras vistas de las paredes calizas del desfiladero.</descripcion>
                <coordenadas>
                    <longitud>-1.310352</longitud>
                    <latitud>42.648980</latitud>
                    <altitud unidad="m">427.2</altitud>
                </coordenadas>
                <distancia unidades="m">167</distancia>
                <fotos>
                    <foto>multimedia/imagenes/RUTA1_HITO1_puente_hierros.jpg</foto>
                </fotos>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.309445</longitud>
                    <latitud>42.648308</latitud>
                    <altitud unidad="m">425.3</altitud>
                </coordenadas>
                <distancia unidades="m">105</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.308312</longitud>
                    <latitud>42.649823</latitud>
                    <altitud unidad="m">421.9</altitud>
                </coordenadas>
                <distancia unidades="m">192</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.307206</longitud>
                    <latitud>42.650296</latitud>
                    <altitud unidad="m">424.9</altitud>
                </coordenadas>
                <distancia unidades="m">105</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.304371</longitud>
                    <latitud>42.650245</latitud>
                    <altitud unidad="m">438.7</altitud>
                </coordenadas>
                <distancia unidades="m">232</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.302320</longitud>
                    <latitud>42.651276</latitud>
                    <altitud unidad="m">434.3</altitud>
                </coordenadas>
                <distancia unidades="m">203</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.301038</longitud>
                    <latitud>42.651257</latitud>
                    <altitud unidad="m">444.8</altitud>
                </coordenadas>
                <distancia unidades="m">105</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.302121</longitud>
                    <latitud>42.650108</latitud>
                    <altitud unidad="m">459.9</altitud>
                </coordenadas>
                <distancia unidades="m">155</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.301280</longitud>
                    <latitud>42.649305</latitud>
                    <altitud unidad="m">475.0</altitud>
                </coordenadas>
                <distancia unidades="m">113</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.301589</longitud>
                    <latitud>42.648882</latitud>
                    <altitud unidad="m">480.9</altitud>
                </coordenadas>
                <distancia unidades="m">53</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.299955</longitud>
                    <latitud>42.648273</latitud>
                    <altitud unidad="m">507.1</altitud>
                </coordenadas>
                <distancia unidades="m">150</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.301080</longitud>
                    <latitud>42.647347</latitud>
                    <altitud unidad="m">522.2</altitud>
                </coordenadas>
                <distancia unidades="m">138</distancia>
            </hito>

            <hito>
                <nombre>Sendero de Cruces V - VIII</nombre>
                <descripcion>Tramo elevado del recorrido en el que se localizan las cruces V a VIII de un antiguo Via Crucis talladas en piedra caliza. Ofrece amplias vistas sobre el valle de Lumbier y los campos de cultivo circundantes.</descripcion>
                <coordenadas>
                    <longitud>-1.300788</longitud>
                    <latitud>42.646967</latitud>
                    <altitud unidad="m">533.1</altitud>
                </coordenadas>
                <distancia unidades="m">49</distancia>
                <fotos>
                    <foto>multimedia/imagenes/RUTA1_HITO2_cruces.jpg</foto>
                </fotos>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.300460</longitud>
                    <latitud>42.645390</latitud>
                    <altitud unidad="m">565.7</altitud>
                </coordenadas>
                <distancia unidades="m">177</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.297289</longitud>
                    <latitud>42.646011</latitud>
                    <altitud unidad="m">613.2</altitud>
                </coordenadas>
                <distancia unidades="m">268</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.295943</longitud>
                    <latitud>42.645773</latitud>
                    <altitud unidad="m">635.7</altitud>
                </coordenadas>
                <distancia unidades="m">113</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.295468</longitud>
                    <latitud>42.644972</latitud>
                    <altitud unidad="m">656.4</altitud>
                </coordenadas>
                <distancia unidades="m">97</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.296602</longitud>
                    <latitud>42.642923</latitud>
                    <altitud unidad="m">711.4</altitud>
                </coordenadas>
                <distancia unidades="m">246</distancia>
            </hito>

            <hito>
                <nombre>Ermita de la Trinidad</nombre>
                <descripcion>Pequeña ermita dedicada a la Santisima Trinidad, enclavada a 724 m de altitud en una posicion privilegiada sobre el valle. Construccion de piedra caliza integrada en el entorno natural y punto de referencia de las antiguas rutas de peregrinacion de la zona.</descripcion>
                <coordenadas>
                    <longitud>-1.296193</longitud>
                    <latitud>42.642087</latitud>
                    <altitud unidad="m">724.6</altitud>
                </coordenadas>
                <distancia unidades="m">99</distancia>
                <fotos>
                    <foto>multimedia/imagenes/RUTA1_HITO3_ermita.jpg</foto>
                </fotos>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.293884</longitud>
                    <latitud>42.641089</latitud>
                    <altitud unidad="m">767.7</altitud>
                </coordenadas>
                <distancia unidades="m">219</distancia>
            </hito>

            <hito>
                <coordenadas>
                    <longitud>-1.289848</longitud>
                    <latitud>42.640110</latitud>
                    <altitud unidad="m">804.4</altitud>
                </coordenadas>
                <distancia unidades="m">348</distancia>
            </hito>

            <hito>
                <coordenadas>
